### ISSUE TITLE
swfstore.js (src) to Bower 

### ISSUE THREAD

**Issue by szegheo** [nfriedly/Javascript-Flash-Cookies#39]
I think it would be reasonable to let the source JavaScript be included in the Bower package. Let me explain why. The typical workflow is that Bower downloads vendors packages, then comes Gulp/Grunt for merging these scripts into one vendors.min.js. There's two choices: take all the minified vendor scripts and just merge them, or take the source scripts and compress+merge them. There's no written rule for Bower packeges, that would say source MUST be included or minified script MUST be included, but it's more common that source IS included. That's why I prefer the source files with uglify+merge method, but this package has no source when downloaded via Bower. Is it possible to fix it? Thank you!

**Comment by nfriedly** [comment]
Yea, I was trying to optimize for a smaller download, but you're right, including source probably is a good idea. It shouldn't be too hard to change, I'll take a look at it here shortly.

**Comment by nfriedly** [comment]
`v2.2.3` should include the src/ directory
