### ISSUE TITLE
bower.json warnings

### ISSUE THREAD

**Issue by szegheo** [nfriedly/Javascript-Flash-Cookies#40]
These warnings are shown on bower install:

```bash
bower flash-cookies#*         invalid-meta The "main" field cannot contain minified files
bower flash-cookies#*         mismatch Version declared in the json (0.0.0-see-package.json) is different than the resolved one (2.2.3)
```

Seems easy to fix, bot I'm not so familiar with bower.json/package.json keys, so I would leave it to you.

**Comment by nfriedly** [comment]
Yea, neither of those are actual issues, but still worth improving all the same.
